### ISSUE TITLE
Prototype non-functional

### ISSUE THREAD

**Issue by mialbu** [bc-ticketing/host-client#3]
Create a non-functional prototype to design first design of the guest-client.

#### Tasks:
- [x] Event creation form
- ~Event modification form~ -> see #6 
- [x] Event list
- ~Event detail component~ -> see #8 
- ~Information component of required approver~ -> see #10 
- [x] Ticket type creation form
- [x] Ticket list
- ~Ticket detail component~ -> see #9 
- [x] Approver registration form
- [x] Approver verification form for manual verification

Crossed items are tackled in other issues.

**Comment by mialbu** [comment]
A non-functional prototype has been done. The components not implemented yet are handled in other issues as linked in the head comment.
I'll close this.
